modLoader="javafml"
loaderVersion="[44,)"
license="All rights reserved"

[[mods]]
    modId="creeperoverhaul"
    version="${version}"
    displayName="Creeper Overhaul"
    logoFile="assets/creeperoverhaul/icon.png"
    authors="Artist/Creator - Joosh, Dev - ThatGravyBoat"
    description="Creeper overhaul adds a variety of different biome-specific creeper types to your world, some friendlier than others :)"

[[dependencies.creeperoverhaul]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.0.3,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,)"
    ordering="NONE"
    side="BOTH"