modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"

[[mods]]
    modId="creeperoverhaul"
    version="${version}"
    displayName="Creeper Overhaul"
    logoFile="icon.png"
    authors="Artist/Creator - Joosh, Dev - ThatGravyBoat"
    description="Creeper overhaul adds a variety of different biome-specific creeper types to your world, some friendlier than others :)"

[[dependencies.creeperoverhaul]]
    modId="geckolib"
    mandatory=true
    versionRange="[3.1.8,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="resourcefulconfig"
    mandatory=true
    versionRange="[1.0.20,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,)"
    ordering="NONE"
    side="BOTH"