modLoader="javafml"
loaderVersion = "[1,)"
license="All rights reserved"

[[mods]]
    modId="creeperoverhaul"
    version="${version}"
    displayName="Creeper Overhaul"
    logoFile="icon.png"
    authors="Artist/Creator - Joosh, Dev - ThatGravyBoat"
    description="Creeper overhaul adds a variety of different biome-specific creeper types to your world, some friendlier than others :)"

[[mixins]]
    config="creeperoverhaul-common.mixins.json"

[[dependencies.creeperoverhaul]]
    modId="geckolib"
    type="required"
    versionRange="[4.5.5,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="resourcefulconfig"
    type="required"
    versionRange="[3.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="neoforge"
    type="required"
    versionRange = "[21.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.creeperoverhaul]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,)"
    ordering="NONE"
    side="BOTH"